export enum DefaultCategory {
  SALARY = 'Зарплата',
  FREELANCE = 'Фриланс',
  BENEFITS = 'Пособия и выплаты',
  OTHER_INCOME = 'Другие доходы',
  FOOD = 'Еда',
  TRANSPORT = 'Транспорт и такси',
  HOUSING = 'Жильё',
  UTILITIES = 'Коммунальные услуги',
  HEALTH = 'Здоровье',
  SHOPPING = 'Покупки',
  ENTERTAINMENT = 'Развлечения',
  EDUCATION = 'Образование',
  SUBSCRIPTIONS = 'Подписки',
  TRAVEL = 'Путешествия',
  GIFTS = 'Подарки',
  OTHER = 'Прочее',
}
